AffinidiHackathon/Models/CreateCredentialViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AffinidiHackathon.Models
{
    public class CreateCredentialViewModel
    {
        public CreateCredentialFormModel Form { get; set; }
    }
}

AffinidiHackathon/Models/MyPendingCredentialsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AffinidiHackathon.Models
{
    public class MyPendingCredentialsViewModel
    {
        public List<BuildSignedVC> Credentials { get; set; }
        public string User { get; set; }
    }
}

AffinidiHackathon/Models/SignUp.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AffinidiHackathon.Models
{
    public class SignUp
    {
        [Required]
        public string username { get; set; }
        [Required]
        public string password { get; set; }
    }
}

AffinidiHackathon/Models/SignupViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AffinidiHackathon.Models
{
    public class SignupViewModel
    {
        public SignUp Form { get; set; }
    }
}

AffinidiHackathon/Controllers/HomeController.cs
using AffinidiHackathon.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace AffinidiHackathon.Controllers
{
    public class HomeController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            if (Session["Username"] != null)
            {
                return RedirectToAction("MyCredentials");
            }
            SignupViewModel model = new SignupViewModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Login(SignUp Form)
        {
            
            SignupViewModel model = new SignupViewModel();
            model.Form = Form;
            var json = JsonConvert.SerializeObject(Form);
            var data = new StringContent(json, Encoding.UTF8, "application/json");

            var url = URLAffinidy + "/users/login";
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Add("Api-Key", HashAffinidy);
                var response = client.PostAsync(url, data).Result;

                string result = response.Content.ReadAsStringAsync().Result;
                var respuesta = JsonConvert.DeserializeObject<ResponseLogin>(result);
                if (respuesta.accessToken != null)
                {
                    AccessToken = respuesta.accessToken;
                    Username = Form.username;
                    HolderDid = respuesta.did;
                    if(!UserDids.ContainsKey(Form.username))
                    {
                        UserDids.Add(Form.username, respuesta.did);
                    }
                    return RedirectToAction("MyCredentials");
                }
                else
                {
                    ViewBag.Error = respuesta.message;
                    return View(model);
                }
            }

        }

        public ActionResult Logoff()
        {
            UserDids.Remove(Username);
            AccessToken = null;
            Username = null;
            Admin = null;
            HolderDid = null;
            return RedirectToAction("Index");
        }

        public ActionResult SignUp()
        {
            SignupViewModel model = new SignupViewModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult SignUp(SignUp Form)
        {
            SignupViewModel model = new SignupViewModel();
            model.Form = Form;
            var json = JsonConvert.SerializeObject(Form);
            var data = new StringContent(json, Encoding.UTF8, "application/json");

            var url = URLAffinidy+ "/users/signup";
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Add("Api-Key", HashAffinidy);
                var response = client.PostAsync(url, data).Result;

                string result = response.Content.ReadAsStringAsync().Result;
                var respuesta = JsonConvert.DeserializeObject<ResponseSignUp>(result);
                if(respuesta.accessToken != null)
                {
                    UserDids.Add(Form.username, respuesta.did);
                    ViewBag.Message = "Successful signup.";
                    return RedirectToAction("Login");
                }
                else
                {
                    ViewBag.Error = respuesta.message;
                    return View(model);
                }
            }

        }

        public ActionResult MyCredentials()
       {
            if(Username == null)
            {
                return RedirectToAction("Login");
            }
            var url = URLAffinidy + "/wallet/credentials";
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Add("Api-Key", HashAffinidy);
                client.DefaultRequestHeaders.Add("Authorization", AccessToken);
                var response = client.GetAsync(url).Result;

                string result = response.Content.ReadAsStringAsync().Result;
                var respuesta = JsonConvert.DeserializeObject<CredentialsUser[]>(result);
                return View(respuesta);
                
            }
        }

        public ActionResult MyPendingCredentials()
        {
            if (Username == null)
            {
                return RedirectToAction("Login");
            }
            MyPendingCredentialsViewModel model = new MyPendingCredentialsViewModel();

            model.Credentials = SignedNotSavedCredentials.ContainsKey(Username)? SignedNotSavedCredentials[Username] : new List<BuildSignedVC>();
            model.User = Username;
            return View(model);
        }

        [HttpPost]
        public ActionResult MyPendingCredentials(string id)
        {
            var credencial = SignedNotSavedCredentials[Username].SingleOrDefault(x => x.signedCredential.id.Replace("claimId:", "") == id);
            var json = JsonConvert.SerializeObject(new { data = new List<SignedCredential>() { credencial.signedCredential } });
            var data = new StringContent(json, Encoding.UTF8, "application/json");

            var url = URLAffinidy + "/wallet/credentials";
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Add("Api-Key", HashAffinidy);
                client.DefaultRequestHeaders.Add("Authorization", AccessToken);
                var response = client.PostAsync(url, data).Result;

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    SignedNotSavedCredentials[Username].Remove(credencial);
                    return RedirectToAction("MyCredentials");
                }

                ViewBag.Error = response.StatusCode.ToString() + ":" + response.Content.ReadAsStringAsync().Result;
                return RedirectToAction("MyPendingCredentials");
            }
            
        }


        public ActionResult Share(string id)
        {
            if (Username == null)
            {
                return RedirectToAction("Login");
            }
            ShareCredentialViewModel model = new ShareCredentialViewModel();
            var url = URLAffinidy + string.Format("/wallet/credentials/claimId:{0}/share",id);
            var json = JsonConvert.SerializeObject(new { ttl="0" });
            var data = new StringContent(json, Encoding.UTF8, "application/json");
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Add("Api-Key", HashAffinidy);
                client.DefaultRequestHeaders.Add("Authorization", AccessToken);
                var response = client.PostAsync(url, data).Result;
                string result = response.Content.ReadAsStringAsync().Result;
                model.Share = JsonConvert.DeserializeObject<ShareCredentialResponse>(result);

                return View(model);
            }
            
        }


        public ActionResult CreateCredential()
        {
            if (Username == null)
            {
                return RedirectToAction("Login");
            }
            CreateCredentialViewModel model = new CreateCredentialViewModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult CreateCredential(CreateCredentialFormModel Form)
        {
            CreateCredentialViewModel model = new CreateCredentialViewModel();
            model.Form = Form;
            Form.type = "NatIDNumCredentialPersonV1";
            if (!ModelState.IsValid)
            {
                
                return View(model);
            }
            string user = UserDids.FirstOrDefault(x => x.Value == HolderDid).Key;

            BuildUnsignedVCRequest requestVC = new BuildUnsignedVCRequest { data = Form, holderDid = HolderDid, type = "NatIDNumCredentialPersonV1" };
            var json = JsonConvert.SerializeObject(requestVC);
            var data = new StringContent(json, Encoding.UTF8, "application/json");

            var url = AffinidyURLIssuer + "/vc/build-unsigned";
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Add("Api-Key", HashAffinidy);
                var response = client.PostAsync(url, data).Result;

                string result = response.Content.ReadAsStringAsync().Result;
                var respuesta = JsonConvert.DeserializeObject<BuildUnsignedVCResponse>(result);
                if(UnsignedCredentials.ContainsKey(user))
                {
                    UnsignedCredentials[user].Add(respuesta);
                }
                else
                {
                    UnsignedCredentials.Add(user, new List<BuildUnsignedVCResponse>() { respuesta });
                }
                
                ViewBag.Message = "Successful signup.";
                return RedirectToAction("CredentialCreated");
            }
        }

        public ActionResult CredentialCreated()
        {
            if (Username == null)
            {
                return RedirectToAction("Login");
            }
            return View();
        }

    }
}

AffinidiHackathon/Controllers/VerifierController.cs
using AffinidiHackathon.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace AffinidiHackathon.Controllers
{
    public class VerifierController : BaseController
    {
        // GET: Verifier
        public ActionResult Index(string urlCredential)
        {
            IndexVerifierViewModel model = new IndexVerifierViewModel();
            if(!string.IsNullOrWhiteSpace(urlCredential))
            {
                model.Url = urlCredential;
                string resultadoCredenciales = string.Empty;

                using (var client = new HttpClient())
                {
                    var response = client.GetAsync(urlCredential).Result;

                    string result = response.Content.ReadAsStringAsync().Result;
                    var respuesta = JsonConvert.DeserializeObject<CredentialShared>(result);
                    model.Credential = respuesta;
                    resultadoCredenciales = result;
                }
                var json = JsonConvert.SerializeObject(new { verifiableCredentials = new List<CredentialShared> { model.Credential } });
                var data = new StringContent(json, Encoding.UTF8, "application/json");
                var url = AffinidyURLVerifier + "/verifier/verify-vcs";
                using (var client = new HttpClient())
                {
                    client.DefaultRequestHeaders.Add("Api-Key", HashAffinidy);
                    var response = client.PostAsync(url, data).Result;

                    string result = response.Content.ReadAsStringAsync().Result;
                    var respuesta = JsonConvert.DeserializeObject<CredentialVerified>(result);
                    model.Verified = respuesta;
                }
            }
            return View(model);
        }

    }
}

AffinidiHackathon/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AffinidiHackathon/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AffinidiHackathon/Views/Home/CredentialCreated.cshtml
@{
    ViewBag.Title = "CredentialCreated";
}

<div class="container col-xl-10 col-xxl-8 px-4 py-5">
    <div class="row align-items-center g-5 py-5">
        <div class="col-md-12 text-center text-lg-start">
            <h1 class="display-4 fw-bold lh-1 mb-3">Your credential was created and now, the issuer from Govern are going to sign this document.</h1>
        </div>
    </div>
</div>

AffinidiHackathon/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Welcome to Immigrant Verifier";
}

<div class="jumbotron">
    <h1>Immigrant Verifier</h1>
    <p class="lead">Immigrant Verifier is a service to obtain, sign and verify credentials for immigrants, avoiding face-to-face bureaucratic processes in consulates or embassies, or for people who leave their countries in search of new opportunities in their destinations.</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Are you an immigrant?</h2>
        <p>
            You can enter here to create your credential, enter your data and that a person from your government can sign it, so that it is valid and you can share it with whoever you want.
        </p>
        <p>@Html.ActionLink("Create credential", "Login", "Home", null, new { @class = "btn btn-primary btn-lg px-4 me-sm-3" })</p>
    </div>
    <div class="col-md-4">
        <h2>Sign credentials as government</h2>
        <p>If you are a government institution, you can create your account and sign the credentials created by your citizens.</p>

        <p>@Html.ActionLink("Sign credentials", "Index", "Admin", null, new { @class = "btn btn-success btn-lg px-4" })</p>
    </div>
    <div class="col-md-4">
        <h2>Verify a credential</h2>
        <p>If you are an institution and you must verify the identity of a person with their credentials, you must enter here</p>
        <p>@Html.ActionLink("Check credentials", "Index", "Verifier", null, new { @class = "btn btn-outline-secondary btn-lg px-4" })</p>
    </div>
</div>

AffinidiHackathon/Views/Home/Login.cshtml
@model AffinidiHackathon.Models.SignupViewModel
@{
    ViewBag.Title = "Login";
}

@ViewBag.Message
@ViewBag.Error




<div class="container col-xl-10 col-xxl-8 px-4 py-5">
    <div class="row align-items-center g-5 py-5">
        <div class="col-lg-7 text-center text-lg-start">
            <h1 class="display-4 fw-bold lh-1 mb-3">Use an account to log in.</h1>
            <p class="col-lg-10 fs-4">You can log in or sign up to create new credentials.</p>
        </div>
        <div class="col-10 mx-auto col-lg-5">
            @using (Html.BeginForm("Login", "Home", null, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <div class="form-floating mb-3">

                    @Html.TextBoxFor(m => m.Form.username, new { @class = "form-control", placeholder = "username",required= "required" })
                    @Html.LabelFor(m => m.Form.username, new { @class = "col-md-2 control-label" })
                    @Html.ValidationMessageFor(m => m.Form.username, "", new { @class = "text-danger" })
                </div>
                <div class="form-floating mb-3">

                    @Html.PasswordFor(m => m.Form.password, new { @class = "form-control", placeholder = "Password", required = "required" })
                    @Html.LabelFor(m => m.Form.password, new { @class = "col-md-2 control-label" })
                    @Html.ValidationMessageFor(m => m.Form.password, "", new { @class = "text-danger" })
                </div>
                <button class="w-100 btn btn-lg btn-primary" type="submit">Login</button>
                <hr class="my-4">
                @Html.ActionLink("Register as a new user", "SignUp", null, new { @class = "btn btn-default" })
            }
        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AffinidiHackathon/Views/Home/MyCredentials.cshtml
@model AffinidiHackathon.Models.CredentialsUser[]

@{
    ViewBag.Title = "My Credentials";
}

@Html.ActionLink("Create a new credential", "CreateCredential", null, new { @class = "btn btn-success btn-lg px-4" })
@Html.ActionLink("View pending credentials to save", "MyPendingCredentials", null, new { @class = "btn btn-info btn-lg px-4" })
<br />
<div class="container col-xl-10 col-xxl-8 px-4 py-5">
    <div class="row align-items-center g-5 py-5">
        <div class="col-lg-4 text-center text-lg-start">
            <h1 class="display-4 fw-bold lh-1 mb-3">My credentials</h1>
            <p class="col-lg-10 fs-4">Here you can view your credentials.</p>
        </div>
        <div class="col-10 mx-auto col-lg-7">
            <table class="table table-striped table-sm">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Birth Date</th>
                        <th>Country</th>
                        <th>City</th>
                        <th>Passport number</th>
                        <th>National Document number</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var credential in Model)
                    {
                        <tr>
                            <td>@credential.credentialSubject.data.Name</td>
                            <td>@credential.credentialSubject.data.BirthDate</td>
                            <td>@credential.credentialSubject.data.Country</td>
                            <td>@credential.credentialSubject.data.City</td>
                            <td>@credential.credentialSubject.data.PassportNumber</td>
                            <td>@credential.credentialSubject.data.NationalDocumentNumber</td>
                            <td>@Html.ActionLink("Share credential", "Share", new { id = credential.id.Replace("claimId:", "") }, new { @class = "btn btn-success btn-lg px-4" })</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

AffinidiHackathon/Views/Home/MyPendingCredentials.cshtml
@model AffinidiHackathon.Models.MyPendingCredentialsViewModel
@{
    ViewBag.Title = "MyPendingCredentials";
}

<div class="container col-xl-10 col-xxl-8 px-4 py-5">
    <div class="row align-items-center g-5 py-5">
        <div class="col-lg-3 text-center text-lg-start">
            <h1 class="display-4 fw-bold lh-1 mb-3">My Pending Credentials</h1>
        </div>
        <div class="col-10 mx-auto col-lg-8">
            <table class="table table-striped table-sm">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var credential in Model.Credentials)
                    {
                        using (Html.BeginForm())
                        {
                        <tr>
                            <td>@Html.Hidden("id", credential.signedCredential.id.Replace("claimId:", "")) @credential.signedCredential.id</td>
                            <td><input type="submit" value="Save in my wallet" class="btn btn-info" /></td>
                        </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

AffinidiHackathon/Views/Home/Share.cshtml
@model AffinidiHackathon.Models.ShareCredentialViewModel

@{
    ViewBag.Title = "Share";
}

         <div class="px-4 py-5 my-5 text-center">
             <h1 class="display-5 fw-bold">Share credentials</h1>
             <div class="col-lg-6 mx-auto">
                 <p class="lead mb-4">
                     Here is the url you can share: <br />
                     <a href="@Model.Share.sharingUrl" target="_blank">@Model.Share.sharingUrl</a>
                 </p>
             </div>
             <div class="col-lg-6 mx-auto">
                 <p class="lead mb-4">
                     And the QR code:<br />
                     <img src="@Model.Share.qrCode" alt="QR code" />
                 </p>
             </div>
         </div>

AffinidiHackathon/Views/Home/SignUp.cshtml
@model AffinidiHackathon.Models.SignupViewModel
@{
    ViewBag.Title = "SignUp";
}


@ViewBag.Message
@ViewBag.Error



<div class="container col-xl-10 col-xxl-8 px-4 py-5">
    <div class="row align-items-center g-5 py-5">
        <div class="col-lg-7 text-center text-lg-start">
            <h1 class="display-4 fw-bold lh-1 mb-3">Create a new account.</h1>
            <p class="col-lg-10 fs-4">Create a new account for testing Immigrant Verifier.</p>
        </div>
        <div class="col-10 mx-auto col-lg-5">
            @using (Html.BeginForm(null,null, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()

                @Html.ValidationSummary("", new { @class = "text-danger" })

                <div class="form-floating mb-3">

                    @Html.TextBoxFor(m => m.Form.username, new { @class = "form-control", placeholder = "username" })
                    @Html.LabelFor(m => m.Form.username, new { @class = "col-md-2 control-label" })
                    @Html.ValidationMessageFor(m => m.Form.username, "", new { @class = "text-danger" })
                </div>
                <div class="form-floating mb-3">

                    @Html.PasswordFor(m => m.Form.password, new { @class = "form-control", placeholder = "Password" })
                    @Html.LabelFor(m => m.Form.password, new { @class = "col-md-2 control-label" })
                    @Html.ValidationMessageFor(m => m.Form.password, "", new { @class = "text-danger" })
                </div>
                <button class="w-100 btn btn-lg btn-primary" type="submit">Register</button>
                <hr class="my-4">
            }
        </div>
    </div>
</div>





@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}